-- MySQL Script generated by MySQL Workbench
-- 01/01/19 23:09:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema heroku_e680d1d8c5e6ace
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heroku_e680d1d8c5e6ace
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heroku_e680d1d8c5e6ace` DEFAULT CHARACTER SET utf8 ;
USE `heroku_e680d1d8c5e6ace` ;

-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`customer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customerName` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `customerAddress` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `customerPhone` VARCHAR(15) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isDelete` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 911
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`driver` (
  `staffId` INT(11) NOT NULL AUTO_INCREMENT,
  `lastTripId` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `longitude` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `latitude` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `isDelete` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`staffId`),
  INDEX `status` (`status` ASC),
  INDEX `FK_drive_Trip` (`lastTripId` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 122
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`drivestatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`drivestatus` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `statusName` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`staff` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fullname` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `phone` VARCHAR(20) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `dob` DOUBLE(20,0) NULL DEFAULT NULL,
  `userType` INT(11) NULL DEFAULT NULL,
  `isDelete` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `userType` (`userType` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 131
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`token` (
  `id_user` INT(11) NULL DEFAULT NULL,
  `refresh_token` VARCHAR(150) NULL DEFAULT NULL,
  `isFrist` INT(11) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `heroku_e680d1d8c5e6ace`.`trip`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heroku_e680d1d8c5e6ace`.`trip` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `customerId` INT(11) NULL DEFAULT NULL,
  `driverId` INT(11) NULL DEFAULT NULL,
  `tripLocation` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tripLongitude` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `tripLatitude` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  `note` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `requestTime` DOUBLE(20,0) NULL DEFAULT NULL,
  `isDelete` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `status` (`status` ASC),
  INDEX `customerId` (`customerId` ASC),
  INDEX `driverId` (`driverId` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 731
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
